baseURL               = "https://front-end.directory.wnor.net"
languageCode          = "zh-CN"
title                 = "å‰ç«¯å¼€å‘èµ„æºå¯¼èˆªğŸ§­"
theme                 = "WebStack-Hugo"
preserveTaxonomyNames = true
disablePathToLower    = true
hasCJKLanguage        = true
publishDir            = "public"				# ç«™ç‚¹é™æ€æ–‡ä»¶ä¿å­˜ç›®å½•


[params]
    author        = "zpsud"
    description   = "å‰ç«¯å¼€å‘èµ„æºå¯¼èˆªğŸ§­"
    upload        = "https://form.google.com"                   # å·¦ä¾§å¯¼èˆªæ çš„"ç½‘ç«™æäº¤"
    about         = "https://github.com/zpsud"	                # å·¦ä¾§å¯¼èˆªæ çš„"å…³äºå¯¼èˆª"é¡µé¢(./about)
    repository    = "https://github.com/zpsud/frontend-directory"  
    contactLink   = false                                       # å³ä¸‹è§’çš„è”ç³»æˆ‘ä»¬é“¾æ¥ï¼Œstring | boolean
    enablePreLoad = true					                    # ç½‘ç«™å®Œå…¨æ‰“å¼€å‰é¢„åŠ è½½åŠ¨ç”»
    textPreLoad   = "å‰ç«¯å¼€å‘èµ„æºå¯¼èˆªğŸ§­"				            # é¢„åŠ è½½çš„åŠ¨ç”»æ–‡å­—, åªæœ‰å½“enablePreLoad=trueæ—¶ç”Ÿæ•ˆ
    expandSidebar = false					                    # é»˜è®¤å±•å¼€å·¦ä¾§è¾¹å¯¼èˆªæ 
    logosPath     = "assets/images/logos"			            # ç½‘ç«™æ¯ä¸ªå¯¼èˆªåœ°å€logoå­˜æ”¾åœ°å€
    defaultLogo   = "assets/images/logos/default.webp"		    # logoå›¾ç‰‡èµ„æºä¸å­˜åœ¨æˆ–è€…é”™è¯¯æ—¶, é»˜è®¤æ˜¾ç¤ºçš„logo; è¯¥å‚æ•°å¦‚ä¸ºç©º,å°†ä¼šä¸€ç›´åŠ è½½å¯¹åº”çš„logo,ç›´è‡³æˆåŠŸ
    nightMode     = true					                    # é»˜è®¤ç«™ç‚¹ä¸ºæ·±è‰²(å¤œé—´)æ¨¡å¼
    yiyan         = true                         		        # é»˜è®¤å¯ç”¨ä¸€è¨€æœåŠ¡

[params.seo]    
    baiduhmid       = ''	                # ç™¾åº¦ç»Ÿè®¡ hm.src çš„ ID
    baiduSiteVer    = ''			        # ç™¾åº¦HTMLæ ‡ç­¾éªŒè¯(baidu-site-verification)
    tj51laid        = ''                    # 51.LA ç½‘ç«™ç»Ÿè®¡
    tj51lack        = ''
    GoogleAdsClient = ''					# Google AdSense 

[params.qweather]
    key = "085791e805a24491b43b06cf58ab31e7"

[params.analytics]
    plausibleScript             = 'https://analysis.wnor.net/script.js'
    plausibleDomain             = 'c7c5f0e5-34db-468f-bda8-b421a39b18f9'
    cloudflareBeaconToken       = 'b34f0d542cc9435eb2a82caab9a87e15'
    cloudflareSpa               = false # true or false

[params.images]
    favicon           = "assets/images/favicon.png"
    searchImageL      = "assets/images/bg-dna.webp"		# æœç´¢éƒ¨åˆ†æµ…è‰²èƒŒæ™¯å›¾
    searchImageD      = "assets/images/bg-dna.webp"		# æœç´¢éƒ¨åˆ†æ·±è‰²èƒŒæ™¯å›¾
    logoExpandLight   = "assets/images/bt8-expand-light.png"
    logoExpandDark    = "assets/images/bt8-expand-dark.png"
    logoCollapseLight = "assets/images/bt.png"
    logoCollapseDark  = "assets/images/bt.png"
    
[markup.goldmark.renderer]
    unsafe = true

[params.footer]
    copyright = 'æœ¬ç«™å†…å®¹æºè‡ªäº’è”ç½‘ï¼Œå¦‚æœ‰å†…å®¹ä¾µçŠ¯äº†ä½ çš„æƒç›Šï¼Œè¯·è”ç³»åˆ é™¤ç›¸å…³å†…å®¹ï¼Œè”ç³»ï¼š<a href="https://github.com/zpsud" class="" target="_blank" data-toggle="tooltip" data-placement="left" title="è”ç³»æˆ‘ä»¬"><i class="mode-ico iconfont icon-github"></i></a> <br/>&copy; {year} By [WebStack-Hugo](https://github.com/shenweiyan/WebStack-Hugo)'
